version: '3'
services:
  app:
    build:
      context: .
# =========ローカルと本番切り替え===========
    command: bundle exec puma -C config/puma.rb -e production
    # command: bundle exec puma -C config/puma.rb
# ======================================
    volumes:
      - .:/awsrails2
      - public-data:/awsrails2/public
      - tmp-data:/awsrails2/tmp
      - log-data:/awsrails2/log
    networks:
      - awsrails2-network
# =========ローカルと本番切り替え===========
  #   depends_on:
  #     - db

  # db:
  #   image: mysql:5.7
  #   environment:
  #     MYSQL_ROOT_PASSWORD: password
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password
  #     MYSQL_DATABASE: awsrails2_development
  #   volumes:
  #     - db-data:/var/lib/mysql
  #   networks:
  #     - awsrails2-network
# ======================================

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/awsrails2/public
      - tmp-data:/awsrails2/tmp
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      - awsrails2-network
volumes:
  public-data:

  tmp-data:
  log-data:
  db-data:

networks:
  awsrails2-network:
    external: true
